name: SBSB Test
on:
  workflow_dispatch:

jobs:
  release:
    name: SBSB Test
    if: github.actor == 'kingthorin' || github.actor == 'psiinon' || github.actor == 'thc202'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Build
      run: cd snap; ./build-snap.sh
