name: Snap Release Test
on:
  workflow_dispatch:

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd snap; ./build-snap.sh
